import React from "react";
import type {PlanoComercial} from "./MercadoReal";
export interface PerfilConcorrente {nome:string;tipo:string;perfil:string;porte_mercado:string;portfolio:string;diferencial:string;precos:string;promocoes:string;canais:string;presenca_digital:string;reputacao:string;ponto_fraco:string;projecoes:{campo:string;estimativa:string;premissas:string}[]}
const linhas:[keyof PerfilConcorrente,string][]=[["perfil","Perfil e localização"],["porte_mercado","Porte e participação"],["portfolio","Produtos e serviços"],["diferencial","Principal diferencial"],["precos","Preço e pagamento"],["promocoes","Promoções e frete"],["canais","Canais de venda e atração"],["presenca_digital","Presença digital"],["reputacao","Atendimento e reputação"],["ponto_fraco","Ponto fraco crítico"]];
export default function AnaliseConcorrencia({concorrentes,plano,data}:{concorrentes:PerfilConcorrente[];plano:Pick<PlanoComercial,"produtos">;data?:string}){
 if(!concorrentes.length)return <p className="my-4 text-sm">A comparação de concorrentes ficará disponível com o diagnóstico do mercado.</p>;
 const referencia:Partial<Record<keyof PerfilConcorrente,string>>={portfolio:plano.produtos?.map(p=>p.produto_nome||p.produto_id).join(", "),diferencial:plano.produtos?.map(p=>p.posicionamento).join(", "),precos:plano.produtos?.map(p=>`${p.produto_nome||p.produto_id}: R$ ${p.preco.toFixed(2)}`).join("; "),canais:plano.produtos?.map(p=>p.canais.join(", ")).join("; ")};
 return <section className="my-5 rounded-xl border p-4"><h3 className="text-lg font-bold">Análise de concorrência · comparação estratégica</h3>{data&&<p className="text-xs">Consulta de mercado: {data.split("-").reverse().join("/")}</p>}<p className="my-3 text-sm">Compare oportunidades e ameaças antes de decidir. Projeções são estimativas, com premissas; uma estratégia inadequada pode reduzir vendas, elevar custos e comprometer o caixa.</p><div className="overflow-x-auto"><table className="min-w-[750px] w-full text-sm"><caption className="sr-only">Concorrentes comparados às escolhas atuais da equipe</caption><thead><tr><th className="p-3 text-left">Parâmetro</th>{concorrentes.map(c=><th className="p-3 text-left" key={c.nome}>{c.nome}<span className="block text-xs font-normal">{c.tipo==="DIRETO"?"Direto":c.tipo==="INDIRETO"?"Indireto":"Cenário projetado"}</span></th>)}<th className="p-3 text-left">Sua empresa · escolhas atuais</th></tr></thead><tbody>{linhas.map(([campo,titulo])=><tr className="border-t" key={campo}><th className="p-3 text-left align-top">{titulo}</th>{concorrentes.map(c=><td className="p-3 align-top whitespace-pre-wrap" key={c.nome}>{String(c[campo]??"Não disponível")}</td>)}<td className="p-3 align-top">{referencia[campo]||"Avaliar e definir pela equipe"}</td></tr>)}</tbody></table></div>{concorrentes.some(c=>c.projecoes.length>0)&&<details className="mt-4"><summary className="font-bold">Projeções e premissas usadas</summary>{concorrentes.map(c=><div key={c.nome}>{c.projecoes.map((p,i)=><article key={i} className="my-3"><h4 className="font-semibold">{c.nome} · {p.campo} · Projeção</h4><p>{p.estimativa}</p><p className="text-sm">Premissas: {p.premissas}</p></article>)}</div>)}</details>}</section>;
}
