import React, {useState} from "react";
import {api} from "../api";
import type {Equipe} from "../tipos";
import {Aviso,Botao,Cartao,estiloEntrada} from "./ui";
export const CARGOS = [{codigo:"CEO",nome:"Direção geral"},{codigo:"CFO",nome:"Finanças"},{codigo:"CMO",nome:"Marketing"},{codigo:"COO",nome:"Operações"},{codigo:"CHRO",nome:"Pessoas"}];
export default function EquipeEmpresa({empresaId,equipe,podeEditar:_podeEditar=false,aoSalvar,rodada=1,encerrada=false}:{empresaId:number;equipe:Equipe;podeEditar?:boolean;aoSalvar?:()=>Promise<unknown>;rodada?:number;encerrada?:boolean}){
 const [escolhido,setEscolhido]=useState(""),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState("");
 const nome=(id:number|null)=>equipe.membros.find(m=>m.aluno_id===id)?.nome??"Ainda não escolhido";
 async function escolher(){setOcupado(true);setErro("");try{await api.post(`/api/aluno/empresas/${empresaId}/lider`,{aluno_id:Number(escolhido),rodada});await aoSalvar?.();setEscolhido("");}catch(e){setErro(e instanceof Error?e.message:"Não foi possível alterar a liderança.");}finally{setOcupado(false);}}
 return <Cartao titulo={`Equipe · ${equipe.membros.length} de 5 integrantes`}><div className="space-y-4"><div className="rounded-xl border-2 border-ouro bg-ouro/10 p-4"><h3 className="text-lg font-bold">Líder nesta rodada: {nome(equipe.lider_id)}</h3><p className="mt-2">Somente o líder registra e envia as decisões construídas com a equipe. Os demais integrantes visualizam os dados e contribuem na discussão.</p><p className="mt-2 font-semibold">A transferência de liderança só passa a valer na próxima rodada.</p>{equipe.proximo_lider_id&&<p className="mt-3 font-bold">Próximo líder: {nome(equipe.proximo_lider_id)} · a partir da rodada {equipe.transferencia_rodada}.</p>}</div>
 <ul className="divide-y">{equipe.membros.map(m=><li key={m.aluno_id} className="py-2">{m.nome}{m.aluno_id===equipe.lider_id?" · Líder":m.aluno_id===equipe.proximo_lider_id?" · Próximo líder":" · Integrante"}</li>)}</ul>
 {!encerrada&&(!equipe.lider_id||equipe.pode_decidir)&&!equipe.proximo_lider_id&&<div className="rounded-xl border p-4"><h3 className="font-bold">{equipe.lider_id?"Transferir liderança":"Escolher o líder inicial"}</h3><p className="my-2 text-sm">{equipe.lider_id?"Combine a troca com a equipe e selecione o integrante que assumirá na próxima rodada.":"Com 3 a 5 integrantes, cada aluno registra sua escolha. O candidato com mais da metade dos votos assume a liderança inicial."}</p><select aria-label="Integrante para liderança" className={estiloEntrada} value={escolhido} onChange={e=>setEscolhido(e.target.value)}><option value="">Selecione um integrante</option>{equipe.membros.filter(m=>m.aluno_id!==equipe.lider_id).map(m=><option key={m.aluno_id} value={m.aluno_id}>{m.nome}</option>)}</select><Botao disabled={ocupado||!escolhido||equipe.membros.length<3} onClick={escolher}>{equipe.lider_id?"Transferir liderança para a próxima rodada":"Registrar minha escolha"}</Botao>{!equipe.lider_id&&<p className="mt-2 text-sm">{Object.keys(equipe.votos_lider).length} escolhas registradas.</p>}</div>}
 {equipe.pendencias.length>0&&<Aviso tipo="info"><ul className="list-disc pl-5">{equipe.pendencias.map(p=><li key={p}>{p}</li>)}</ul></Aviso>}{equipe.pronta&&<Aviso tipo="sucesso">O líder enviou a decisão final. A equipe está pronta para o fechamento.</Aviso>}{erro&&<Aviso>{erro}</Aviso>}
 <a className="text-sm underline" href="/manuais/manual-aluno.pdf" target="_blank" rel="noreferrer">Consultar o manual: equipe, liderança e envio</a>
 {!!equipe.historico.length&&<details><summary>Histórico da equipe</summary><ul className="mt-3 max-h-64 overflow-auto text-sm">{[...equipe.historico].reverse().map((h,i)=><li className="py-2" key={i}>{h.aluno} · {h.acao.replace(/_/g," ").toLowerCase()} · rodada {h.rodada} · {new Date(h.data).toLocaleString("pt-BR")}</li>)}</ul></details>}
 </div></Cartao>;
}
