import React,{useEffect,useState} from "react";
import {api} from "../api";
import type {Turma} from "../tipos";
import {Aviso,Botao,Cartao,estiloEntrada} from "./ui";
interface Formacao {disponiveis:{aluno_id:number;nome:string}[];inscritos:{aluno_id:number;nome:string;autorizada_turma_id:number|null}[];turmas_destino:{id:number;nome:string}[];equipes:{empresa_id:number;nome:string;vagas:number}[]}
export default function FormacaoTurma({turma,aoAtualizar}:{turma:Turma;aoAtualizar:()=>Promise<unknown>}){
 const [dados,setDados]=useState<Formacao|null>(null),[mensagem,setMensagem]=useState(""),[ocupado,setOcupado]=useState(false);
 const [aluno,setAluno]=useState(""),[destino,setDestino]=useState(""),[empresa,setEmpresa]=useState(""),[motivo,setMotivo]=useState("");
 async function carregar(){try{setDados(await api.get(`/api/professor/turmas/${turma.id}/formacao`));}catch(e){setMensagem(e instanceof Error?e.message:"Erro ao carregar participantes.");}}
 useEffect(()=>{carregar();const intervalo=window.setInterval(carregar,15000);return()=>window.clearInterval(intervalo);},[turma.id]);
 async function agir(fn:()=>Promise<unknown>){setOcupado(true);setMensagem("");try{const resposta=await fn() as {mensagem?:string;distribuicao?:{aluno:string;empresa:string}[]};setMensagem(resposta.mensagem??"Configuração atualizada.");if(resposta.distribuicao?.length)setMensagem(`${resposta.mensagem} ${resposta.distribuicao.map(a=>`${a.aluno} → ${a.empresa}`).join("; ")}`);await aoAtualizar();await carregar();}catch(e){setMensagem(e instanceof Error?e.message:"Não foi possível concluir.");}finally{setOcupado(false);}}
 return <Cartao titulo="Ingresso e formação das equipes"><div className="space-y-4"><p>Os alunos selecionam a turma pelo nome. Você controla se ela aparece para ingresso; ocultá-la não retira o acesso de quem já entrou.</p><label className="flex items-center gap-2"><input type="checkbox" disabled={ocupado} checked={turma.visivel_ingresso} onChange={e=>agir(()=>api.put(`/api/professor/turmas/${turma.id}/ingresso`,{visivel_ingresso:e.target.checked,formacao_encerrada:turma.formacao_encerrada}))}/>Disponível para ingresso dos alunos</label>
 <p className="font-bold">{dados?.disponiveis.length??0} alunos sem equipe: {dados?.disponiveis.map(a=>a.nome).join(", ")||"nenhum"}</p><p>Depois de perguntar se todos entraram, distribua os alunos restantes aleatoriamente entre equipes com no mínimo 3 integrantes e no máximo 5. Se faltarem vagas, organize novas equipes.</p>
 {turma.modo_equipe&&turma.rodada_atual===1&&<><Botao disabled={ocupado||turma.formacao_encerrada} onClick={()=>agir(()=>api.post(`/api/professor/turmas/${turma.id}/distribuir-sem-equipe`,{}))}>Encerrar formação e distribuir alunos sem equipe</Botao>{turma.formacao_encerrada&&<Botao variante="secundario" disabled={ocupado} onClick={()=>agir(()=>api.put(`/api/professor/turmas/${turma.id}/ingresso`,{visivel_ingresso:turma.visivel_ingresso,formacao_encerrada:false}))}>Reabrir formação</Botao>}</>}
 <details><summary className="font-bold">Autorizar troca de turma ou inclusão excepcional</summary><p className="my-3 text-sm">Use a inclusão manual apenas para resolver um impedimento do aluno. Registre a justificativa. A troca autoriza o aluno a selecionar o destino, sem apagar o histórico anterior.</p><label>Aluno<select className={estiloEntrada} value={aluno} onChange={e=>setAluno(e.target.value)}><option value="">Selecione</option>{dados?.inscritos.map(a=><option key={a.aluno_id} value={a.aluno_id}>{a.nome}</option>)}</select></label><label>Justificativa<textarea className={estiloEntrada} maxLength={1000} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><label>Turma de destino<select className={estiloEntrada} value={destino} onChange={e=>setDestino(e.target.value)}><option value="">Selecione</option>{dados?.turmas_destino.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></label><Botao disabled={ocupado||!aluno||!destino||motivo.trim().length<5} onClick={()=>agir(()=>api.post(`/api/professor/turmas/${turma.id}/autorizar-troca`,{aluno_id:Number(aluno),destino_id:Number(destino),motivo}))}>Autorizar troca</Botao><label>Equipe para inclusão excepcional<select className={estiloEntrada} value={empresa} onChange={e=>setEmpresa(e.target.value)}><option value="">Selecione</option>{dados?.equipes.filter(e=>e.vagas>0).map(e=><option key={e.empresa_id} value={e.empresa_id}>{e.nome} · {e.vagas} vagas</option>)}</select></label><Botao variante="secundario" disabled={ocupado||!aluno||!empresa||motivo.trim().length<5} onClick={()=>agir(()=>api.post(`/api/professor/turmas/${turma.id}/inclusao-excepcional`,{aluno_id:Number(aluno),empresa_id:Number(empresa),motivo}))}>Registrar inclusão excepcional</Botao></details>
 {mensagem&&<Aviso tipo="info">{mensagem}</Aviso>}</div></Cartao>;
}
