import React, { useEffect, useState } from "react";
import { api } from "../api";
import { Cartao, estiloEntrada } from "./ui";
import { reais } from "../formatos";
interface Midia { id:string; nome:string; categoria:string; descricao:string; quando_usar:string; unidade:string; preco_unitario:number; exemplo:string; cuidado:string }
export default function ManualMidias(){
 const [midias,setMidias]=useState<Midia[]>([]),[busca,setBusca]=useState(""),[categoria,setCategoria]=useState("Todas"),[erro,setErro]=useState("");
 useEffect(()=>{api.get<{midias:Midia[]}>("/api/educacao/manual-midias").then(d=>setMidias(d.midias)).catch(e=>setErro(e.message));},[]);
 const exibidas=midias.filter(m=>(categoria==="Todas"||m.categoria===categoria)&&`${m.nome} ${m.descricao}`.toLocaleLowerCase().includes(busca.toLocaleLowerCase()));
 return <Cartao titulo="Manual de mídias · entenda antes de investir"><p className="mb-4">Consulte os formatos do catálogo de campanhas. Escolha pela afinidade com o público, pelo objetivo e pelo caixa disponível. Os valores são referências didáticas do jogo.</p><a className="mb-4 inline-block font-bold text-blue-700 underline" href="/manuais/manual-midias.pdf" target="_blank" rel="noreferrer">Abrir manual completo em PDF →</a><div className="mb-4 grid gap-3 sm:grid-cols-3">{[['CPM','Custo por mil impressões. Quantidade 10 compra 10 mil exibições; uma pessoa pode ver mais de uma vez.'],['CPC e visualização','CPC compra cliques. CPV compra visualizações conforme a regra da tabela. Cliques e visualizações não são vendas.'],['Inserções e pacotes','Inserção é uma veiculação. Parceria, licença e pacote são unidades próprias. Produção e veiculação podem ser cobradas separadamente.']].map(([t,d])=><article key={t} className="rounded-xl bg-blue-50 p-4"><h3 className="font-bold">{t}</h3><p className="mt-2 text-sm">{d}</p></article>)}</div><div className="mb-4 grid gap-3 sm:grid-cols-2"><label>Buscar mídia<input className={estiloEntrada} value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Ex.: carrossel, rádio, influenciador…"/></label><label>Categoria<select className={estiloEntrada} value={categoria} onChange={e=>setCategoria(e.target.value)}>{['Todas',...Array.from(new Set(midias.map(m=>m.categoria)))].map(c=><option key={c}>{c}</option>)}</select></label></div>{erro&&<p role="alert">{erro}</p>}<p className="mb-3 text-sm">{exibidas.length} formatos encontrados</p><div className="grid gap-3 lg:grid-cols-2">{exibidas.map(m=><article key={m.id} className="rounded-xl border-2 border-blue-100 bg-white p-4"><p className="text-xs font-bold text-blue-700">{m.categoria}</p><h3 className="my-2 text-lg font-bold">{m.nome}</h3><p>{m.descricao}</p><p className="mt-3 text-sm"><strong>Quando considerar:</strong> {m.quando_usar}</p><p className="mt-2 text-sm"><strong>Compra no jogo:</strong> {reais(m.preco_unitario)} / {m.unidade}. Quantidade × preço unitário.</p><p className="mt-2 text-xs text-slate-600">{m.cuidado}</p></article>)}</div>{!erro&&!exibidas.length&&<p>Nenhuma mídia encontrada. Ajuste os filtros.</p>}</Cartao>;
}
