"""Valores didáticos da tabela de referência fornecida para a simulação."""
CAMPANHAS = [
 ("jornal-inteira","Jornal · página inteira","Impressa",8500,"inserção"),
 ("jornal-meia","Jornal · meia página","Impressa",4500,"inserção"),
 ("revista-inteira","Revista · página inteira","Impressa",12000,"inserção"),
 ("jornal-dupla","Jornal · página dupla","Impressa",9000,"inserção"),
 ("revista-dupla","Revista · página dupla","Impressa",12500,"inserção"),
 ("jornal-fracao","Jornal · fração de página","Impressa",450,"inserção"),
 ("revista-fracao","Revista · fração de página","Impressa",650,"inserção"),
 ("revista-meia","Revista · meia página","Impressa",6000,"inserção"),
 ("influenciador-micro","Influenciador · até 100 mil seguidores","Digital",1200,"parceria"),
 ("influenciador-medio","Influenciador · 100 a 500 mil seguidores","Digital",3500,"parceria"),
 ("influenciador-grande","Influenciador · mais de 500 mil seguidores","Digital",8000,"parceria"),
 ("email","E-mail marketing","Digital",.12,"envio"),
 ("podcast","Podcast · inserção","Digital",800,"inserção"),
 ("sms","SMS marketing","Digital",.10,"envio"),
 ("conteudo","Marketing de conteúdo","Digital",1500,"pacote mensal"),
 ("google","Google Ads","Digital",750,"campanha"),
 ("meta","Meta Ads","Digital",900,"campanha"),
 ("bumper","YouTube · bumper","Digital",14,"mil impressões"),
 ("skippable","YouTube · in-stream","Digital",.25,"visualização"),
 ("stories","Stories / Reels / TikTok","Digital",16,"mil impressões"),
 ("feed","Feed · Instagram / Facebook / LinkedIn","Digital",20,"mil impressões"),
 ("carrossel","Carrossel","Digital",1.20,"clique"),
 ("colecao","Anúncio de coleção","Digital",25,"mil impressões"),
 ("push","Notificação push","Digital",300,"licença"),
 ("outdoor","Outdoor fixo","Exterior",1700,"painel"),
 ("frontlight","Front light","Exterior",4000,"painel"),
 ("busdoor","Busdoor","Exterior",900,"veículo"),
 ("painel","Painel digital","Exterior",1400,"painel"),
 ("mobiliario","Mobiliário urbano","Exterior",1650,"painel"),
 ("empena","Empena","Exterior",45000,"estrutura"),
 ("frota","Envelopamento de frota","Exterior",23000,"veículo"),
 ("telas","Telas · elevador / táxi / metrô","Exterior",1800,"circuito"),
 ("radio-spot","Rádio · spot 30 segundos","Eletrônica",500,"inserção"),
 ("radio-testemunhal","Rádio · testemunhal","Eletrônica",1200,"inserção"),
 ("tv15","TV · comercial 15 segundos","Eletrônica",18000,"inserção"),
 ("tv30","TV · comercial 30 segundos","Eletrônica",30000,"inserção"),
 ("cinema","Cinema · comercial 30 segundos","Eletrônica",12000,"inserção"),
 ("teaser","TV · teaser","Eletrônica",4500,"inserção"),
 ("merchandising","TV · merchandising","Eletrônica",27000,"ação"),
 ("vinheta","TV · vinheta de patrocínio","Eletrônica",47000,"cota mensal"),
 ("infocomercial","TV · infocomercial","Eletrônica",6000,"inserção"),
 ("jingle","Rádio · produção de jingle","Eletrônica",2400,"produção"),
 ("radio-patrocinio","Rádio · patrocínio de programa","Eletrônica",4750,"cota mensal"),
 ("radio-streaming","Rádio · streaming","Eletrônica",40,"mil reproduções"),
 ("radio-social","Rádio · publicação social","Eletrônica",900,"publicação"),
 ("carro-som","Carro de som","Direto",350,"ação"),
 ("flyer-impressao","Panfletos · impressão","Direto",.22,"unidade"),
 ("flyer-distribuicao","Panfletos · distribuição","Direto",.18,"unidade"),
 ("mala","Mala direta","Direto",1.50,"peça"),
 ("telemarketing","Telemarketing","Direto",1500,"campanha mensal"),
 ("assessoria","Assessoria de imprensa","Relações públicas",3800,"mês"),
 ("release","Comunicado à imprensa","Relações públicas",280,"release"),
 ("brindes","Brindes","Promoção",8,"unidade"),
 ("placement","Product placement simples","Product placement",6000,"ação"),
 ("placement-premium","Product placement premium","Product placement",18000,"ação"),
 ("leaderboard","Leaderboard 728×90","Display",10,"mil impressões"),
 ("mpu","Retângulo médio 300×250","Display",12,"mil impressões"),
 ("halfpage","Half page 300×600","Display",17,"mil impressões"),
 ("skyscraper","Skyscraper 160×600","Display",8,"mil impressões"),
 ("billboard","Billboard 970×250","Display",21,"mil impressões"),
 ("interstitial","Interstitial","Display",35,"mil impressões"),
 ("native","Native Ads","Display",.50,"clique"),
]

def catalogo():
    from .manual_midias import DESCRICOES
    from .servicos_midias import metadados
    return [dict(id=i,nome=n,categoria=c,preco_unitario=p,unidade=u,descricao=DESCRICOES[i],**metadados(i)) for i,n,c,p,u in CAMPANHAS]
