"""Guia didático do catálogo efetivamente usado nas campanhas."""
DESCRICOES={
'jornal-inteira':'Anúncio que ocupa uma página inteira de jornal. Dá espaço para uma mensagem detalhada e alcance no público leitor.',
'jornal-meia':'Anúncio em metade de uma página de jornal. Permite combinar informação e presença com custo menor que a página inteira.',
'revista-inteira':'Página completa em revista. Útil para públicos ligados ao tema da publicação e para apresentar atributos visuais do produto.',
'jornal-dupla':'Anúncio nas duas páginas abertas do jornal. Prioriza impacto visual e visibilidade.',
'revista-dupla':'Anúncio em duas páginas abertas de revista. Permite uma composição visual ampla para uma campanha de marca.',
'jornal-fracao':'Espaço pequeno, como um quarto de página ou rodapé de jornal. Adequado a mensagens curtas e ofertas locais.',
'revista-fracao':'Espaço pequeno em revista. Dá presença em um público temático sem comprar uma página inteira.',
'revista-meia':'Metade de uma página de revista, em formato horizontal ou vertical. Equilibra espaço e custo.',
'influenciador-micro':'Parceria paga com criador de conteúdo de até 100 mil seguidores. Pode aproximar a marca de um nicho; avalie aderência e engajamento, não só seguidores.',
'influenciador-medio':'Parceria com criador de 100 a 500 mil seguidores. Combina alcance e possibilidade de trabalhar públicos temáticos.',
'influenciador-grande':'Parceria com criador acima de 500 mil seguidores. Busca amplo alcance; audiência grande não garante intenção de compra.',
'email':'Mensagem enviada a uma lista de contatos com permissão. Útil para relacionamento, recompra e ofertas; não confundir envios com mensagens abertas.',
'podcast':'Menção ou anúncio dentro de um episódio de podcast. A seleção do programa deve considerar o tema e o perfil dos ouvintes.',
'sms':'Mensagem curta enviada ao celular. Pode divulgar ofertas ou avisos; exige contatos autorizados e linguagem objetiva.',
'conteudo':'Pacote de produção de textos, imagens ou vídeos para canais próprios. Ajuda a explicar produtos e construir confiança ao longo do tempo.',
'google':'Campanha de anúncios no Google, em pesquisa, display ou YouTube. Pesquisa atende intenção de busca; display e vídeo trabalham presença e lembrança.',
'meta':'Campanha de anúncios no Facebook e Instagram. Permite segmentação e diferentes objetivos; atenção à frequência e à coerência da oferta.',
'bumper':'Vídeo de até seis segundos no YouTube, não pulável. Exige uma mensagem curta e serve para reforçar lembrança.',
'skippable':'Vídeo in-stream pulável após os primeiros segundos. Apresente a proposta cedo; a tabela do jogo cobra por visualização.',
'stories':'Vídeo ou imagem vertical para Stories, Reels ou TikTok. Formato móvel que exige comunicação rápida e visual.',
'feed':'Imagem ou vídeo entre publicações de Instagram, Facebook ou LinkedIn. A mensagem deve fazer sentido no contexto de cada rede.',
'carrossel':'Sequência de imagens ou vídeos deslizantes. Permite mostrar variantes, benefícios ou etapas; no jogo a compra é por clique.',
'colecao':'Anúncio com peça principal e catálogo de produtos. Facilita descoberta e navegação para compra online.',
'push':'Licença para enviar notificações curtas de aplicativo ou navegador a usuários que autorizaram o recebimento. A licença não equivale a alcance garantido.',
'outdoor':'Painel fixo em via de circulação. Comunica rapidamente a quem passa; use pouco texto e contraste forte.',
'frontlight':'Painel com iluminação frontal. Ajuda a manter a visibilidade noturna; localização e circulação são relevantes.',
'busdoor':'Anúncio aplicado na parte externa de ônibus. Circula por trajetos urbanos e oferece exposição repetida.',
'painel':'Painel de LED que exibe anúncios e permite alternar peças. Adequado a comunicação visual breve em pontos de circulação.',
'mobiliario':'Anúncio em abrigos de ônibus, relógios e outros mobiliários de rua. Alcança pedestres e pessoas em deslocamento.',
'empena':'Grande anúncio em parede lateral de prédio. Busca impacto visual, mas envolve estrutura e produção de maior custo.',
'frota':'Adesivagem de veículos, ônibus ou vagões. Transforma a superfície do veículo em exposição da marca.',
'telas':'Circuito de telas em elevadores, táxis ou metrô. Exposição durante esperas e deslocamentos; considere que pode não haver áudio.',
'radio-spot':'Anúncio de áudio gravado com 30 segundos. Permite repetição e divulgação de ofertas; cada inserção é uma veiculação.',
'radio-testemunhal':'Anúncio lido por apresentador ou locutor. Usa a identificação da audiência com o programa, com publicidade claramente reconhecível.',
'tv15':'Comercial de 15 segundos em televisão. Requer mensagem curta e execução visual clara.',
'tv30':'Comercial de 30 segundos em televisão. Oferece mais tempo para explicar a proposta ou demonstrar o produto.',
'cinema':'Comercial de 30 segundos antes da sessão de cinema. Trabalha presença audiovisual em um ambiente de atenção.',
 'teaser':'Vídeo curto que cria expectativa sobre um lançamento. Precisa de continuidade para explicar a oferta posteriormente.',
'merchandising':'Ação comercial integrada a um programa, com apresentação ou interação com o produto. Deve ser identificada como publicidade.',
'vinheta':'Mensagem breve de patrocínio na abertura ou fechamento de um bloco. A tabela compra uma cota mensal.',
'infocomercial':'Demonstração publicitária longa, normalmente de 15 a 30 minutos. Explica uso e benefícios com mais profundidade.',
'jingle':'Produção de música curta publicitária. O custo desta linha é a criação; a veiculação em rádio exige contratar inserções separadamente.',
'radio-patrocinio':'Cota mensal de associação da marca a um programa de rádio. Pode incluir chamadas e vinhetas conforme o pacote.',
'radio-streaming':'Anúncio de áudio em plataformas digitais de rádio ou streaming. A tabela compra lotes de mil reproduções.',
'radio-social':'Publicação nos perfis sociais da emissora. É uma ação digital distinta das inserções no rádio.',
'carro-som':'Divulgação por veículo com alto-falante em uma região. É uma ação local; observe adequação ao público e regras de ruído.',
'flyer-impressao':'Produção física de panfletos. Imprimir não significa distribuir; a distribuição é uma linha separada.',
'flyer-distribuicao':'Entrega dos panfletos em locais de circulação. Este custo não inclui a impressão do material.',
'mala':'Material impresso enviado por correio. Na tabela do jogo o custo por peça inclui impressão e postagem.',
'telemarketing':'Campanha mensal de contato telefônico. Adequada a ofertas que precisam de conversa; use contatos autorizados e respeite preferências.',
'assessoria':'Serviço mensal de relacionamento com a imprensa e preparação de pautas. Busca cobertura editorial, sem garantir publicação.',
'release':'Preparação e envio de comunicado oficial à imprensa. A compra de um release não é compra de espaço editorial.',
'brindes':'Objetos promocionais com a marca entregues ao público. O custo é por unidade e a utilidade do item influencia sua lembrança.',
'placement':'Presença do produto em uma cena de conteúdo audiovisual. A marca aparece no contexto, sem ser necessariamente um comercial separado.',
'placement-premium':'Inserção destacada ou recorrente em conteúdo audiovisual. Busca maior destaque que a inserção simples.',
'leaderboard':'Banner horizontal de 728×90 pixels, normalmente no topo de uma página web. A cobrança no jogo é por mil impressões.',
'mpu':'Banner retangular de 300×250 pixels, integrado ao conteúdo ou à lateral de uma página. É um formato comum de display.',
'halfpage':'Banner vertical de 300×600 pixels. Oferece grande área visual na lateral da página.',
'skyscraper':'Banner vertical estreito de 160×600 pixels. Ocupa uma faixa lateral da página.',
'billboard':'Banner grande de 970×250 pixels, normalmente no topo. Busca destaque em telas maiores.',
'interstitial':'Anúncio que ocupa a tela entre etapas de navegação. Tem grande visibilidade, mas pode interromper a experiência do usuário.',
'native':'Anúncio que acompanha o formato visual do conteúdo de um site. Deve permanecer identificado como publicidade; no jogo é comprado por clique.'
}
USOS={'Impressa':'Públicos locais ou temáticos; mensagem informativa e presença visual.','Digital':'Busca, descoberta ou relacionamento conforme o canal e o estágio de compra.','Exterior':'Lembrança da marca e alcance geográfico próximo à circulação do público.','Eletrônica':'Campanhas audiovisuais e exposição por programação ou audiência.','Direto':'Contato direcionado e divulgação local.','Relações públicas':'Credibilidade e relacionamento com veículos de comunicação.','Promoção':'Contato e lembrança da marca por meio de objetos úteis.','Product placement':'Associação da marca ao contexto de conteúdo audiovisual.','Display':'Exposição visual em sites e aplicativos.'}

def guia():
    from .catalogo_campanhas import CAMPANHAS
    return [dict(id=i,nome=n,categoria=c,preco_unitario=p,unidade=u,descricao=DESCRICOES[i],quando_usar=USOS[c],exemplo=f'10 {u}: R$ {p*10:.2f}.',cuidado='Valores didáticos da simulação; alcance, cliques e vendas são resultados diferentes. Produção e condições reais de contratação podem variar.') for i,n,c,p,u in CAMPANHAS]
